package View;
//data

import com.mysql.cj.protocol.Resultset;
import database.database_two;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author mahar
 */
public class LaporanRental extends javax.swing.JPanel {

    /**
     * Creates new form MenuDashboard
     */
    private int HalamanSaatIni = 1;
    private int DataperHalaman = 14;
    private int totalpages;

    private final Connection con;// Koneksi database

    private String userID;

    // Konstruktor kelas MenuKonsol
    public LaporanRental(String userID) {
        con = database_two.con(); // Membuat koneksi ke database
        this.userID = userID;
        initComponents(); // Inisialisasi komponen GUI
        loadData(); // Memuat data Konsol ke dalam JTable
        setTabelModel(); // Mengatur model tabel (misalnya, kolom-kolomnya)
        resetForm(); // Mereset form input menjadi kosong
        paginationKonsol(); // Mengatur paginasi untuk tampilan data
        actionButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        dateChooser2 = new com.raven.datechooser.DateChooser();
        panelMain = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new Palette.JTable_Custom();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_tampilkan = new Palette.Custom_ButtonRounded();
        txt_search = new Palette.JTextfieldRounded();
        btn_first = new javax.swing.JButton();
        btn_before = new javax.swing.JButton();
        cbx_data = new javax.swing.JComboBox<>();
        btn_next = new javax.swing.JButton();
        btn_last = new javax.swing.JButton();
        lb_halaman = new javax.swing.JLabel();
        txt_tanggal_mulai = new Palette.JTextfieldRounded();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_tanggal_sampai = new Palette.JTextfieldRounded();
        btn_batal = new Palette.Custom_ButtonRounded();
        btn_cetak = new Palette.Custom_ButtonRounded();

        dateChooser1.setTextRefernce(txt_tanggal_mulai);

        dateChooser2.setTextRefernce(txt_tanggal_sampai);

        setLayout(new java.awt.CardLayout());

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setBackground(new java.awt.Color(255, 255, 255));

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tbl_data.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tbl_data.setSelectionForeground(new java.awt.Color(204, 255, 51));
        jScrollPane1.setViewportView(tbl_data);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Transaksi.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Data Selesai Rental");

        btn_tampilkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add.png"))); // NOI18N
        btn_tampilkan.setText("Tampilkan");
        btn_tampilkan.setFillClick(new java.awt.Color(0, 51, 102));
        btn_tampilkan.setFillOver(new java.awt.Color(41, 128, 185));
        btn_tampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tampilkanActionPerformed(evt);
            }
        });

        txt_search.setForeground(new java.awt.Color(102, 102, 102));
        txt_search.setText("Search");
        txt_search.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N

        btn_first.setText("First Page");

        btn_before.setText("<");

        cbx_data.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "16", "32", "64" }));

        btn_next.setText(">");

        btn_last.setText("Last Page");
        btn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });

        lb_halaman.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lb_halaman.setForeground(new java.awt.Color(153, 153, 153));
        lb_halaman.setText("Halaman of Total Halaman");

        txt_tanggal_mulai.setForeground(new java.awt.Color(102, 102, 102));
        txt_tanggal_mulai.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        txt_tanggal_mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tanggal_mulaiActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Tanggal Mulai");

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Tanggal Sampai");

        txt_tanggal_sampai.setForeground(new java.awt.Color(102, 102, 102));
        txt_tanggal_sampai.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        txt_tanggal_sampai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tanggal_sampaiActionPerformed(evt);
            }
        });

        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add.png"))); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.setFillClick(new java.awt.Color(0, 51, 102));
        btn_batal.setFillOver(new java.awt.Color(41, 128, 185));
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        btn_cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add.png"))); // NOI18N
        btn_cetak.setText("Cetak");
        btn_cetak.setFillClick(new java.awt.Color(0, 51, 102));
        btn_cetak.setFillOver(new java.awt.Color(41, 128, 185));
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addComponent(btn_first)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_before)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_next)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_last))
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(lb_halaman)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_tanggal_mulai, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(59, 59, 59))
                                    .addComponent(txt_tanggal_sampai, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_tampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tanggal_mulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tanggal_sampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_tampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_halaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_first)
                    .addComponent(btn_before)
                    .addComponent(cbx_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_next)
                    .addComponent(btn_last))
                .addGap(15, 15, 15))
        );

        panelMain.add(panelView, "card2");

        add(panelMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lastActionPerformed

    private void txt_tanggal_mulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tanggal_mulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tanggal_mulaiActionPerformed

    private void btn_tampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tampilkanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tampilkanActionPerformed

    private void txt_tanggal_sampaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tanggal_sampaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tanggal_sampaiActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Palette.Custom_ButtonRounded btn_batal;
    private javax.swing.JButton btn_before;
    private Palette.Custom_ButtonRounded btn_cetak;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_next;
    private Palette.Custom_ButtonRounded btn_tampilkan;
    private javax.swing.JComboBox<String> cbx_data;
    private com.raven.datechooser.DateChooser dateChooser1;
    private com.raven.datechooser.DateChooser dateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_halaman;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelView;
    private Palette.JTable_Custom tbl_data;
    private Palette.JTextfieldRounded txt_search;
    private Palette.JTextfieldRounded txt_tanggal_mulai;
    private Palette.JTextfieldRounded txt_tanggal_sampai;
    // End of variables declaration//GEN-END:variables

    // paginationKonsol() - Mengatur fungsi pagination untuk Konsol
    private void paginationKonsol() {
        // Mengatur tombol halaman pertama
        btn_first.addActionListener(e -> {
            HalamanSaatIni = 1;// Set ke halaman pertama
            loadData(); // Memuat data pada halaman pertama
        });

        // Mengatur tombol halaman sebelumnya
        btn_before.addActionListener(e -> {
            if (HalamanSaatIni > 1) {// Memastikan halaman saat ini lebih dari 1
                HalamanSaatIni--; // Turun ke halaman sebelumnya
                loadData();// Memuat data pada halaman saat ini
            }
        });

        // Mengatur combo box untuk jumlah data per halaman
        cbx_data.addActionListener(e -> {
            DataperHalaman = Integer.parseInt(cbx_data.getSelectedItem().toString());// Mengambil jumlah data per halaman dari combo box
            HalamanSaatIni = 1;// Set ke halaman pertama setiap kali data per halaman diubah
            loadData(); //Memuat data
        });

        // Mengatur tombol halaman berikutnya
        btn_next.addActionListener(e -> {
            if (HalamanSaatIni < totalpages) {// Memastikan belum di halaman terakhir
                HalamanSaatIni++;// Naik ke halaman berikutnya
                loadData();//Memuat data pada halaman baru
            }
        });

        // Mengatur tombol halaman terakhir
        btn_last.addActionListener(e -> {
            HalamanSaatIni = totalpages;// Set ke halaman terakhir
            loadData();// Memuat data pada halaman terakhir
        });

    }

    private void actionButton() {
        btn_tampilkan.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });

        btn_batal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });

        btn_cetak.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });

        txt_search.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                searchData();
            }
        });
    }

// calculateTotalPage() - Menghitung total halaman berdasarkan jumlah data dan data per halaman
    private void calculateTotalPage() {
        int totalData = getTotalData(); // Mendapatkan total data
        totalpages = (int) Math.ceil((double) totalData / DataperHalaman); // Menghitung total halaman
    }

// getTotalData() - Mendapatkan total data dari tabel selesai
    private int getTotalData() {
        int totalData = 0;
        try {
            String sql = "SELECT COUNT(*) AS total FROM tbl_rental"; // Query menghitung total data
            try (PreparedStatement st = con.prepareStatement(sql)) {
                ResultSet rs = st.executeQuery(); // Eksekusi query
                if (rs.next()) {
                    totalData = rs.getInt("total"); // Mendapatkan jumlah total dari kolom "total"
                }
            }
        } catch (Exception e) {
            Logger.getLogger(LaporanRental.class.getName()).log(Level.SEVERE, null, e);
        }
        return totalData; // Mengembalikan jumlah data
    }

// loadData() - Memuat data dari tabel selesai ke dalam JTable
    private void loadData() {
        calculateTotalPage(); // Menghitung total halaman
        int totalData = getTotalData(); // Mendapatkan total data
        lb_halaman.setText(String.valueOf("Halaman " + HalamanSaatIni + " Dari total data " + totalData)); // Menampilkan halaman saat ini

        int startIndex = (HalamanSaatIni - 1) * DataperHalaman; // Menentukan indeks awal data
        getData(startIndex, DataperHalaman, (DefaultTableModel) tbl_data.getModel()); // Mendapatkan data untuk ditampilkan di tabel
    }

// showPanel() - Mengatur tampilan panel utama
    private void showPanel() {
        panelMain.removeAll(); // Menghapus semua komponen di panel utama
        panelMain.add(new LaporanRental(userID)); // Menambahkan panel MenuSelesai ke panel utama
        panelMain.repaint(); // Menggambar ulang panel utama
        panelMain.revalidate(); // Memastikan perubahan diterapkan
    }

// resetForm() - Mengosongkan input form
    private void resetForm() {

    }

// setTabelModel() - Mengatur model tabel dengan kolom yang sesuai
    private void setTabelModel() {
        String[] columnNames = {
            "No",
            "ID_Rental",
            "Tanggal Rental",
            "Nama Pelanggan",
            "Jumlah Rental",
            "Durasi",
            "Total Harga",
            "Bayar",
            "Kembalian",
            "Status Rental",
            "Nama Konsol",
            "Tanggal Selesai",};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0); // Membuat model tabel dengan kolom yang ditentukan
        tbl_data.setModel(model); // Mengatur model tabel untuk JTable
        loadData(); // Memuat data ke dalam tabel
    }

// getData() - Mendapatkan data dari tabel selesai dengan batasan jumlah data per halaman
    private void getData(int startIndex, int entriesPage, DefaultTableModel model) {
        model.setRowCount(0); // Mengosongkan data yang ada di tabel

        try {
            String sql = "SELECT "
                    + "r.ID_Rental, "
                    + "r.Tanggal_Rental, "
                    + "p.Nama AS Nama_Pelanggan, "
                    + "dr.Jumlah_Rental, "
                    + "dr.Durasi, "
                    + "r.Total_Harga, "
                    + "r.Bayar, "
                    + "r.Kembalian, "
                    + "dr.Status_Rental, "
                    + "k.Nama_konsol, "
                    + "s.Tanggal_Selesai "
                    + "FROM tbl_rental r "
                    + "INNER JOIN tbl_pelanggan p ON r.ID_Pelanggan = p.ID_Pelanggan "
                    + "INNER JOIN tbl_detail_rental dr ON r.ID_Rental = dr.ID_Rental "
                    + "INNER JOIN tbl_konsol k ON dr.ID_Konsol = k.ID_Konsol "
                    + "INNER JOIN tbl_selesai s ON dr.ID_Rental = s.ID_Rental "
                    + "WHERE dr.Status_Rental = 'Sudah Selesai' "
                    + "ORDER BY r.Tanggal_Rental DESC "
                    + "LIMIT ? OFFSET ?;"; // Use LIMIT and OFFSET for pagination

            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setInt(1, entriesPage); // Jumlah data per halaman
                st.setInt(2, startIndex); // Indeks awal

                ResultSet rs = st.executeQuery(); // Eksekusi query
                int no = startIndex + 1; // Nomor baris dimulai dari indeks

                while (rs.next()) {
                    // Ambil data dari ResultSet
                    String IdRental = rs.getString("ID_Rental");
                    String TanggalRental = rs.getString("Tanggal_Rental");
                    String NamaPelanggan = rs.getString("Nama_Pelanggan");
                    String JumlahRental = rs.getString("Jumlah_Rental");
                    String Durasi = rs.getString("Durasi");
                    String TotalHarga = rs.getString("Total_Harga");
                    String Bayar = rs.getString("Bayar");
                    String Kembalian = rs.getString("Kembalian");
                    String NamaKonsol = rs.getString("Nama_konsol");
                    String StatusRental = rs.getString("Status_Rental");
                    String TanggalSelesai = rs.getString("Tanggal_Selesai");

                    // Tambahkan data ke model tabel
                    Object[] rowData = {
                        "   " + no++, IdRental, TanggalRental, NamaPelanggan, JumlahRental, Durasi, TotalHarga, Bayar, Kembalian, NamaKonsol, StatusRental, TanggalSelesai
                    };
                    model.addRow(rowData); // Menambahkan baris data ke dalam tabel
                }
            }
        } catch (Exception e) {
            Logger.getLogger(LaporanRental.class.getName()).log(Level.SEVERE, null, e);
        }
    }

// insertData() - Menambahkan data ke tabel selesai
//    private void insertData() {
//        String IdSelesai = txt_id.getText();
//        String tanggal = txt_tanggal.getText();
//        String IdRental = txt_id_rental.getText();
//
//        // Insert data ke database
//        try {
//            String sql = "INSERT INTO tbl_selesai (ID_Selesai, Tanggal_Selesai, ID_Rental, ID_User) VALUES (?,?,?,?)";
//            try (PreparedStatement st = con.prepareStatement(sql)) {
//                st.setString(1, IdSelesai);
//                st.setString(2, tanggal);
//                st.setString(3, IdRental);
//                st.setString(4, userID);
//
//                int rowInserted = st.executeUpdate(); // Menjalankan perintah insert
//                if (rowInserted > 0) {
//                    JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
//                }
//            }
//        } catch (SQLException e) {
//            Logger.getLogger(LaporanRental.class.getName()).log(Level.SEVERE, null, e);
//        }
//    }
// updateStatus() - Memperbarui status rental
//    private void updateStatus() {
//        String IdRental = txt_id_rental.getText();
//        String statusRental = "Sudah Selesai";
//
//        try {
//            String sql = "UPDATE tbl_detail_Rental SET Status_Rental=? WHERE ID_Rental=?";
//            try (PreparedStatement st = con.prepareStatement(sql)) {
//                st.setString(1, statusRental);
//                st.setString(2, IdRental);
//
//                int rowsUpdated = st.executeUpdate();
//                if (rowsUpdated > 0) {
//                    JOptionPane.showMessageDialog(this, "Status Rental berhasil diperbarui");
//                }
//            }
//        } catch (SQLException e) {
//            Logger.getLogger(LaporanRental.class.getName()).log(Level.SEVERE, null, e);
//            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memperbarui status Rental", "Error", JOptionPane.ERROR_MESSAGE);
//        }
//    }
// searchData() - Mencari data berdasarkan ID Rental atau Nama User
    private void searchData() {
        String kataKunci = txt_search.getText();

        DefaultTableModel model = (DefaultTableModel) tbl_data.getModel();
        model.setRowCount(0);

        try {
            String sql = "SELECT png.ID_Selesai, png.Tanggal_Selesai, sw.ID_Rental, usr.Nama_User "
                    + "FROM tbl_selesai png "
                    + "INNER JOIN tbl_Rental sw ON sw.ID_Rental = png.ID_Rental "
                    + "INNER JOIN tbl_user usr ON usr.ID_User = png.ID_User "
                    + "WHERE png.ID_Selesai LIKE ? OR usr.Nama_User LIKE ?";
            try (PreparedStatement st
                    = con.prepareStatement(sql)) {
                st.setString(1, "%" + kataKunci + "%");
                st.setString(2, "%" + kataKunci + "%");
                ResultSet rs = st.executeQuery();

                int no = 1;

                while (rs.next()) {
                    String IdSelesai = rs.getString("ID_Selesai");
                    String TanggalSelesai = rs.getString("Tanggal_Selesai");
                    String IdRental = rs.getString("ID_Rental");
                    String NamaUser = rs.getString("Nama_User");

                    Object[] rowData = {"   " + no++, IdSelesai, TanggalSelesai, IdRental, NamaUser};
                    model.addRow(rowData);
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(LaporanRental.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void getDataDetail(DefaultTableModel model, String id) {
        model.setRowCount(0); // Mengosongkan data yang ada di tabel

        try {
            String sql = "SELECT png.ID_Selesai, sw.ID_Rental, usr.Nama_User "
                    + "FROM tbl_selesai png "
                    + "INNER JOIN tbl_Rental sw ON sw.ID_Rental = png.ID_Rental "
                    + "INNER JOIN tbl_user usr ON usr.ID_User = png.ID_User "
                    + "WHERE png.ID_Selesai = ?";

            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, id); // Menggunakan parameter untuk ID_Selesai
                ResultSet rs = st.executeQuery(); // Eksekusi query

                int no = 1; // Nomor urut

                while (rs.next()) {
                    String IdSelesai = rs.getString("ID_Selesai");
                    String IdRental = rs.getString("ID_Rental");
                    String NamaUser = rs.getString("Nama_User");

                    // Tambahkan ke model tabel
                    Object[] rowData = {"   " + no++, IdSelesai, IdRental, NamaUser};
                    model.addRow(rowData);
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(LaporanRental.class.getName()).log(Level.SEVERE, "Error SQL: ", e);
        }
    }

    private String setIdSelesai() throws SQLException {
        String urutan = null;
        Date now = new Date();
        SimpleDateFormat noFormat = new SimpleDateFormat("yyMM"); // Format tanggal sebagai bagian dari ID
        String no = noFormat.format(now);

        String sql = "SELECT RIGHT(ID_Selesai, 3) AS Nomor FROM tbl_selesai WHERE ID_Selesai LIKE '" + no + "%' ORDER BY ID_Selesai DESC LIMIT 1";

        try (PreparedStatement st = con.prepareStatement(sql)) {
            ResultSet rs = st.executeQuery(); // Eksekusi query

            if (rs.next()) {
                int nomor = Integer.parseInt(rs.getString("Nomor")) + 1; // Menambah nomor urut
                urutan = no + String.format("%03d", nomor); // Format ID baru
            } else {
                urutan = no + "001"; // ID awal jika tidak ada data
            }
        } catch (SQLException e) {
            java.util.logging.Logger.getLogger(LaporanRental.class.getName()).log(Level.SEVERE, null, e);
        }
        return urutan;
    }
}
