package View;
//data

import com.mysql.cj.protocol.Resultset;
import database.database_two;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author mahar
 */
public class MenuSewa extends javax.swing.JPanel {

    /**
     * Creates new form MenuDashboard
     */
    private int HalamanSaatIni = 1;
    private int DataperHalaman = 14;
    private int totalpages;

    private final Connection con;// Koneksi database

    private String userID;

    // Konstruktor kelas MenuKonsol
    public MenuSewa(String userID) {
        con = database_two.con(); // Membuat koneksi ke database
        this.userID = userID;
        initComponents(); // Inisialisasi komponen GUI
        loadData(); // Memuat data Konsol ke dalam JTable
        loadDataSementara();
        setTabelModel(); // Mengatur model tabel (misalnya, kolom-kolomnya)
        setTabelModelSementara();
        resetForm(); // Mereset form input menjadi kosong
        resetFormKonsol();
        paginationKonsol(); // Mengatur paginasi untuk tampilan data
        actionButton();
        setTabelModelDetail();
        setColumnWidth();
    }

    private void setColumnWidth() {
//        TableColumnModel columnModel = tbl_data.getColumnModel();
//        columnModel.getColumn(0).setPreferredWidth(40);
//        columnModel.getColumn(0).setMaxWidth(40);
//        columnModel.getColumn(0).setMinWidth(40);
//
//        TableColumnModel columnModel2 = tbl_data_detail.getColumnModel();
//        columnModel2.getColumn(0).setPreferredWidth(40);
//        columnModel2.getColumn(0).setMaxWidth(40);
//        columnModel2.getColumn(0).setMinWidth(40);

        TableColumnModel columnModel3 = tbl_data_sementara.getColumnModel();
        columnModel3.getColumn(0).setPreferredWidth(40);
        columnModel3.getColumn(0).setMaxWidth(40);
        columnModel3.getColumn(0).setMinWidth(40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        dateChooser2 = new com.raven.datechooser.DateChooser();
        panelMain = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new Palette.JTable_Custom();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_tambah = new Palette.Custom_ButtonRounded();
        txt_search = new Palette.JTextfieldRounded();
        btn_first = new javax.swing.JButton();
        btn_before = new javax.swing.JButton();
        cbx_data = new javax.swing.JComboBox<>();
        btn_next = new javax.swing.JButton();
        btn_last = new javax.swing.JButton();
        lb_halaman = new javax.swing.JLabel();
        pn_detail = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_data_detail = new Palette.JTable_Custom();
        btn_cancel_detail = new Palette.Custom_ButtonRounded();
        panelAdd = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_simpan = new Palette.Custom_ButtonRounded();
        btn_batal_add = new Palette.Custom_ButtonRounded();
        panelcustom1 = new Palette.Panelcustom();
        jLabel8 = new javax.swing.JLabel();
        txt_id = new Palette.JTextfieldRounded();
        jLabel9 = new javax.swing.JLabel();
        txt_tgl_sewa = new Palette.JTextfieldRounded();
        txt_tgl_kembali = new Palette.JTextfieldRounded();
        jLabel10 = new javax.swing.JLabel();
        panelcustom2 = new Palette.Panelcustom();
        jLabel11 = new javax.swing.JLabel();
        txt_id_pelanggan = new Palette.JTextfieldRounded();
        jLabel12 = new javax.swing.JLabel();
        txt_nama_pelanggan = new Palette.JTextfieldRounded();
        jLabel13 = new javax.swing.JLabel();
        txt_tlp_pelanggan = new Palette.JTextfieldRounded();
        jLabel14 = new javax.swing.JLabel();
        txt_alamat = new Palette.JTextfieldRounded();
        btn_set_pelanggan = new Palette.Custom_ButtonRounded();
        panelcustom4 = new Palette.Panelcustom();
        jLabel19 = new javax.swing.JLabel();
        txt_id_konsol = new Palette.JTextfieldRounded();
        jLabel20 = new javax.swing.JLabel();
        txt_nama_konsol = new Palette.JTextfieldRounded();
        jLabel21 = new javax.swing.JLabel();
        txt_harga_perhari = new Palette.JTextfieldRounded();
        btn_set_konsol = new Palette.Custom_ButtonRounded();
        panelcustom5 = new Palette.Panelcustom();
        jLabel23 = new javax.swing.JLabel();
        txt_jumlah = new Palette.JTextfieldRounded();
        lb_totalSewa = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btn_ubah = new Palette.Custom_ButtonRounded();
        btn_hapus = new Palette.Custom_ButtonRounded();
        btn_cancel_sementara = new Palette.Custom_ButtonRounded();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_data_sementara = new Palette.JTable_Custom();

        dateChooser1.setTextRefernce(txt_tgl_sewa);

        dateChooser2.setTextRefernce(txt_tgl_kembali);

        setLayout(new java.awt.CardLayout());

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setBackground(new java.awt.Color(255, 255, 255));

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tbl_data.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tbl_data.setSelectionForeground(new java.awt.Color(204, 255, 51));
        jScrollPane1.setViewportView(tbl_data);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Transaksi.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Data Transaksi Sewa");

        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add.png"))); // NOI18N
        btn_tambah.setText("Tambah");
        btn_tambah.setFillClick(new java.awt.Color(0, 51, 102));
        btn_tambah.setFillOver(new java.awt.Color(41, 128, 185));

        txt_search.setForeground(new java.awt.Color(102, 102, 102));
        txt_search.setText("Search");
        txt_search.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N

        btn_first.setText("First Page");

        btn_before.setText("<");

        cbx_data.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "16", "32", "64" }));

        btn_next.setText(">");

        btn_last.setText("Last Page");
        btn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });

        lb_halaman.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lb_halaman.setForeground(new java.awt.Color(153, 153, 153));
        lb_halaman.setText("Halaman of Total Halaman");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Data Detail Sewa");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Transaksi.png"))); // NOI18N

        tbl_data_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tbl_data_detail.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tbl_data_detail.setSelectionForeground(new java.awt.Color(204, 255, 51));
        jScrollPane3.setViewportView(tbl_data_detail);

        btn_cancel_detail.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancel_detail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Multiply.png"))); // NOI18N
        btn_cancel_detail.setFillClick(new java.awt.Color(255, 255, 255));
        btn_cancel_detail.setFillOriginal(new java.awt.Color(255, 255, 255));
        btn_cancel_detail.setFillOver(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_detailLayout = new javax.swing.GroupLayout(pn_detail);
        pn_detail.setLayout(pn_detailLayout);
        pn_detailLayout.setHorizontalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cancel_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pn_detailLayout.setVerticalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btn_cancel_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelViewLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pn_detail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58))))
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addComponent(btn_first)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_before)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_next)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_last))
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(lb_halaman)))
                .addGap(0, 374, Short.MAX_VALUE))
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_halaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_first)
                    .addComponent(btn_before)
                    .addComponent(cbx_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_next)
                    .addComponent(btn_last))
                .addGap(18, 18, 18)
                .addComponent(pn_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelMain.add(panelView, "card2");

        panelAdd.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Icon2.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Transaksi Sewa");

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.setFillClick(new java.awt.Color(0, 51, 102));
        btn_simpan.setFillOver(new java.awt.Color(41, 128, 185));

        btn_batal_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cancel.png"))); // NOI18N
        btn_batal_add.setText("Batal");
        btn_batal_add.setFillClick(new java.awt.Color(153, 51, 0));
        btn_batal_add.setFillOriginal(new java.awt.Color(255, 102, 0));
        btn_batal_add.setFillOver(new java.awt.Color(204, 102, 0));

        panelcustom1.setBackground(new java.awt.Color(250, 250, 250));
        panelcustom1.setRoundBottomRight(20);
        panelcustom1.setRoundBottomleft(20);
        panelcustom1.setRoundTopLeft(20);
        panelcustom1.setRoundTopRight(20);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("ID");

        txt_id.setForeground(new java.awt.Color(102, 102, 102));
        txt_id.setText("ID");
        txt_id.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Tanggal Sewa");

        txt_tgl_sewa.setForeground(new java.awt.Color(102, 102, 102));
        txt_tgl_sewa.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        txt_tgl_sewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tgl_sewaActionPerformed(evt);
            }
        });

        txt_tgl_kembali.setForeground(new java.awt.Color(102, 102, 102));
        txt_tgl_kembali.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Tanggal Kembali");

        javax.swing.GroupLayout panelcustom1Layout = new javax.swing.GroupLayout(panelcustom1);
        panelcustom1.setLayout(panelcustom1Layout);
        panelcustom1Layout.setHorizontalGroup(
            panelcustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_tgl_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_tgl_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        panelcustom1Layout.setVerticalGroup(
            panelcustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcustom1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(panelcustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tgl_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txt_tgl_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(panelcustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelcustom2.setBackground(new java.awt.Color(250, 250, 250));
        panelcustom2.setRoundBottomRight(20);
        panelcustom2.setRoundBottomleft(20);
        panelcustom2.setRoundTopLeft(20);
        panelcustom2.setRoundTopRight(20);

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Pelanggan");

        txt_id_pelanggan.setForeground(new java.awt.Color(102, 102, 102));
        txt_id_pelanggan.setText("ID");
        txt_id_pelanggan.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        txt_id_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_pelangganActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Nama");

        txt_nama_pelanggan.setForeground(new java.awt.Color(102, 102, 102));
        txt_nama_pelanggan.setText("Nama_Pelanggan");
        txt_nama_pelanggan.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        txt_nama_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_pelangganActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Telepon");

        txt_tlp_pelanggan.setForeground(new java.awt.Color(102, 102, 102));
        txt_tlp_pelanggan.setText("Telepon");
        txt_tlp_pelanggan.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Alamat");

        txt_alamat.setForeground(new java.awt.Color(102, 102, 102));
        txt_alamat.setText("Alamat");
        txt_alamat.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N

        btn_set_pelanggan.setText("...");

        javax.swing.GroupLayout panelcustom2Layout = new javax.swing.GroupLayout(panelcustom2);
        panelcustom2.setLayout(panelcustom2Layout);
        panelcustom2Layout.setHorizontalGroup(
            panelcustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcustom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addGroup(panelcustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcustom2Layout.createSequentialGroup()
                        .addComponent(txt_id_pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_set_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_nama_pelanggan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txt_tlp_pelanggan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelcustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelcustom2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelcustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(284, Short.MAX_VALUE)))
        );
        panelcustom2Layout.setVerticalGroup(
            panelcustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcustom2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_set_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txt_nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_tlp_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelcustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelcustom2Layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        panelcustom4.setBackground(new java.awt.Color(250, 250, 250));
        panelcustom4.setRoundBottomRight(20);
        panelcustom4.setRoundBottomleft(20);
        panelcustom4.setRoundTopLeft(20);
        panelcustom4.setRoundTopRight(20);

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Konsol");

        txt_id_konsol.setForeground(new java.awt.Color(102, 102, 102));
        txt_id_konsol.setText("ID");
        txt_id_konsol.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Nama");

        txt_nama_konsol.setForeground(new java.awt.Color(102, 102, 102));
        txt_nama_konsol.setText("Nama_Konsol");
        txt_nama_konsol.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Harga Perhari");

        txt_harga_perhari.setForeground(new java.awt.Color(102, 102, 102));
        txt_harga_perhari.setText("Harga_Perhari");
        txt_harga_perhari.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N

        btn_set_konsol.setText("...");
        btn_set_konsol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_set_konsolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelcustom4Layout = new javax.swing.GroupLayout(panelcustom4);
        panelcustom4.setLayout(panelcustom4Layout);
        panelcustom4Layout.setHorizontalGroup(
            panelcustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcustom4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelcustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelcustom4Layout.createSequentialGroup()
                        .addComponent(txt_id_konsol, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_set_konsol, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_nama_konsol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_harga_perhari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        panelcustom4Layout.setVerticalGroup(
            panelcustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcustom4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_id_konsol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_set_konsol, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelcustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_nama_konsol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelcustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_harga_perhari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelcustom5.setBackground(new java.awt.Color(250, 250, 250));
        panelcustom5.setRoundBottomRight(20);
        panelcustom5.setRoundBottomleft(20);
        panelcustom5.setRoundTopLeft(20);
        panelcustom5.setRoundTopRight(20);

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Jumlah");

        txt_jumlah.setForeground(new java.awt.Color(102, 102, 102));
        txt_jumlah.setText("Jumlah");
        txt_jumlah.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N

        lb_totalSewa.setFont(new java.awt.Font("Poppins Light", 1, 30)); // NOI18N
        lb_totalSewa.setForeground(new java.awt.Color(102, 102, 102));
        lb_totalSewa.setText("TOTAL");

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Total Sewa");

        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        btn_ubah.setText("Simpan");
        btn_ubah.setFillClick(new java.awt.Color(0, 51, 102));
        btn_ubah.setFillOver(new java.awt.Color(41, 128, 185));

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Delete.png"))); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.setFillClick(new java.awt.Color(153, 0, 51));
        btn_hapus.setFillOriginal(new java.awt.Color(255, 0, 51));
        btn_hapus.setFillOver(new java.awt.Color(204, 0, 51));
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_cancel_sementara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cancel.png"))); // NOI18N
        btn_cancel_sementara.setText("Batal");
        btn_cancel_sementara.setFillClick(new java.awt.Color(153, 51, 0));
        btn_cancel_sementara.setFillOriginal(new java.awt.Color(255, 102, 0));
        btn_cancel_sementara.setFillOver(new java.awt.Color(204, 102, 0));

        javax.swing.GroupLayout panelcustom5Layout = new javax.swing.GroupLayout(panelcustom5);
        panelcustom5.setLayout(panelcustom5Layout);
        panelcustom5Layout.setHorizontalGroup(
            panelcustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcustom5Layout.createSequentialGroup()
                .addGroup(panelcustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcustom5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancel_sementara, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lb_totalSewa))
                    .addGroup(panelcustom5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelcustom5Layout.setVerticalGroup(
            panelcustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcustom5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelcustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcustom5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelcustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cancel_sementara, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcustom5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_totalSewa)
                        .addContainerGap())))
        );

        tbl_data_sementara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tbl_data_sementara.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tbl_data_sementara.setSelectionForeground(new java.awt.Color(204, 255, 51));
        jScrollPane2.setViewportView(tbl_data_sementara);

        javax.swing.GroupLayout panelAddLayout = new javax.swing.GroupLayout(panelAdd);
        panelAdd.setLayout(panelAddLayout);
        panelAddLayout.setHorizontalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelcustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_batal_add, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createSequentialGroup()
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelcustom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelcustom4, javax.swing.GroupLayout.PREFERRED_SIZE, 371, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(panelcustom5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelAddLayout.setVerticalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_batal_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelcustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createSequentialGroup()
                        .addComponent(panelcustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createSequentialGroup()
                        .addComponent(panelcustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelcustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelMain.add(panelAdd, "card2");

        add(panelMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_set_konsolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_set_konsolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_set_konsolActionPerformed

    private void txt_id_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_pelangganActionPerformed

    private void txt_nama_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_pelangganActionPerformed

    private void txt_tgl_sewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tgl_sewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tgl_sewaActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lastActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_hapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Palette.Custom_ButtonRounded btn_batal_add;
    private javax.swing.JButton btn_before;
    private Palette.Custom_ButtonRounded btn_cancel_detail;
    private Palette.Custom_ButtonRounded btn_cancel_sementara;
    private javax.swing.JButton btn_first;
    private Palette.Custom_ButtonRounded btn_hapus;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_next;
    private Palette.Custom_ButtonRounded btn_set_konsol;
    private Palette.Custom_ButtonRounded btn_set_pelanggan;
    private Palette.Custom_ButtonRounded btn_simpan;
    private Palette.Custom_ButtonRounded btn_tambah;
    private Palette.Custom_ButtonRounded btn_ubah;
    private javax.swing.JComboBox<String> cbx_data;
    private com.raven.datechooser.DateChooser dateChooser1;
    private com.raven.datechooser.DateChooser dateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_halaman;
    private javax.swing.JLabel lb_totalSewa;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelView;
    private Palette.Panelcustom panelcustom1;
    private Palette.Panelcustom panelcustom2;
    private Palette.Panelcustom panelcustom4;
    private Palette.Panelcustom panelcustom5;
    private javax.swing.JPanel pn_detail;
    private Palette.JTable_Custom tbl_data;
    private Palette.JTable_Custom tbl_data_detail;
    private Palette.JTable_Custom tbl_data_sementara;
    private Palette.JTextfieldRounded txt_alamat;
    private Palette.JTextfieldRounded txt_harga_perhari;
    private Palette.JTextfieldRounded txt_id;
    private Palette.JTextfieldRounded txt_id_konsol;
    private Palette.JTextfieldRounded txt_id_pelanggan;
    private Palette.JTextfieldRounded txt_jumlah;
    private Palette.JTextfieldRounded txt_nama_konsol;
    private Palette.JTextfieldRounded txt_nama_pelanggan;
    private Palette.JTextfieldRounded txt_search;
    private Palette.JTextfieldRounded txt_tgl_kembali;
    private Palette.JTextfieldRounded txt_tgl_sewa;
    private Palette.JTextfieldRounded txt_tlp_pelanggan;
    // End of variables declaration//GEN-END:variables

    // paginationKonsol() - Mengatur fungsi pagination untuk Konsol
    private void paginationKonsol() {
        // Mengatur tombol halaman pertama
        btn_first.addActionListener(e -> {
            HalamanSaatIni = 1;// Set ke halaman pertama
            loadData(); // Memuat data pada halaman pertama
        });

        // Mengatur tombol halaman sebelumnya
        btn_before.addActionListener(e -> {
            if (HalamanSaatIni > 1) {// Memastikan halaman saat ini lebih dari 1
                HalamanSaatIni--; // Turun ke halaman sebelumnya
                loadData();// Memuat data pada halaman saat ini
            }
        });

        // Mengatur combo box untuk jumlah data per halaman
        cbx_data.addActionListener(e -> {
            DataperHalaman = Integer.parseInt(cbx_data.getSelectedItem().toString());// Mengambil jumlah data per halaman dari combo box
            HalamanSaatIni = 1;// Set ke halaman pertama setiap kali data per halaman diubah
            loadData(); //Memuat data
        });

        // Mengatur tombol halaman berikutnya
        btn_next.addActionListener(e -> {
            if (HalamanSaatIni < totalpages) {// Memastikan belum di halaman terakhir
                HalamanSaatIni++;// Naik ke halaman berikutnya
                loadData();//Memuat data pada halaman baru
            }
        });

        // Mengatur tombol halaman terakhir
        btn_last.addActionListener(e -> {
            HalamanSaatIni = totalpages;// Set ke halaman terakhir
            loadData();// Memuat data pada halaman terakhir
        });

    }

    private void actionButton() {
        btn_tambah.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panelMain.removeAll();
                panelMain.add(panelAdd);
                panelMain.repaint();
                panelMain.revalidate();

                // Disable tombol simpan awalnya
                btn_ubah.setText("TAMBAH"); // Default teks tombol ubah

                try {
                    // Set ID untuk txt_id
                    String idSewa = setIDSewa();
                    txt_id.setText(idSewa);
                    txt_id.setEnabled(false); // Disable input txt_id

                    // Ubah teks tombol simpan jika kondisi terpenuhi
                    if ("UBAH".equals(btn_tambah.getText())) {
                        btn_simpan.setText("PERBARUI");
                    } else {
                        btn_simpan.setText("SIMPAN");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(MenuSewa.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Gagal mengatur ID sewa: " + ex.getMessage());
                }
            }
        });

        btn_simpan.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (btn_simpan.getText().equals("TAMBAH")) {
                    btn_simpan.setText("SIMPAN");
                } else if (btn_simpan.getText().equals("SIMPAN")) {
                    insertData();
                } else if (btn_simpan.getText().equals("PERBARUI")) {
                    updateData();
                    resetForm();
                    loadData();
                    showPanel();
                }
            }
        });

        btn_ubah.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (btn_ubah.getText().equals("TAMBAH")) {
                    insertDataSementara();

                } else if (btn_ubah.getText().equals("UBAH")) {
                    updateData();
                }
            }
        });

        btn_hapus.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                hapusData();
            }
        });

        btn_cancel_sementara.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loadDataSementara();
                resetFormKonsol();
                btn_ubah.setText("TAMBAH");
            }
        });

        btn_batal_add.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel();
                loadData();
            }
        });

        btn_cancel_detail.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel();
                loadData();
            }
        });

        txt_search.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                searchData();
            }
        });

        tbl_data.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tbl_data.getSelectedRow(); // Ambil baris yang diklik

                // Cek apakah ada baris yang dipilih
                if (row >= 0) {
                    pn_detail.setVisible(true); // Tampilkan panel detail

                    // Ambil data berdasarkan baris yang dipilih
                    String id = tbl_data.getValueAt(row, 1).toString();
                    getDataDetail((DefaultTableModel) tbl_data_detail.getModel(), id);
                } else {
                    // Tidak ada baris yang dipilih, tampilkan log atau pesan
                    Logger.getLogger(MenuSewa.class.getName()).log(Level.WARNING, "Tidak ada baris yang dipilih!");
                }
            }
        });

        tbl_data_sementara.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                btn_ubah.setText("UBAH");
                btn_hapus.setVisible(true);
                btn_cancel_sementara.setVisible(true);
                dataTabelSementara();
            }
        });

        btn_set_pelanggan.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setPelanggan();
            }
        });

        btn_set_konsol.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setKonsol();
            }
        });

        txt_jumlah.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (btn_ubah.getText().equals("TAMBAH")) {
                    insertDataSementara();
                } else if (btn_ubah.getText().equals("UBAH")) {
                    updateData();
                }
            }
        });
    }

    // calculateTotalPage() - Menghitung total halaman berdasarkan jumlah data dan data per halaman
    private void calculateTotalPage() {
        int totalData = getTotalData();// Mendapatkan total data Konsol
        totalpages = (int) Math.ceil((double) totalData / DataperHalaman);// Menghitung total halaman
    }

    // getTotalData() - Mendapatkan total data Konsol dari database
    private int getTotalData() {
        int totalData = 0;
        try {
            String sql = "SELECT COUNT(*) AS total FROM tbl_konsol";// Query menghitung total data Konsol
            try (PreparedStatement st = con.prepareStatement(sql)) {
                ResultSet rs = st.executeQuery(); // Eksekusi query
                if (rs.next()) {
                    totalData = rs.getInt("total");// Mendapatkan jumlah total dari kolom "total"
                }
            }
        } catch (Exception e) {
            Logger.getLogger(MenuSewa.class.getName()).log(Level.SEVERE, null, e);
        }
        return totalData;// Mengembalikan jumlah data
    }

    // loadData() - Memuat data Konsol ke dalam JTable berdasarkan halaman saat ini
    private void loadData() {
        calculateTotalPage();// Menghitung total halaman
        int totalData = getTotalData();// Mendapatkan total data Konsol
        lb_halaman.setText(String.valueOf("Halaman " + HalamanSaatIni + " Dari total data " + totalData)); // Menampilkan halaman saat ini

        int startIndex = (HalamanSaatIni - 1) * DataperHalaman;// Menentukan indeks awal data berdasarkan halaman saat ini
        getData(startIndex, DataperHalaman, (DefaultTableModel) tbl_data.getModel());// Mendapatkan data untuk ditampilkan di tabel
        btn_hapus.setVisible(false); // Menyembunyikan tombol hapus
        pn_detail.setVisible(false);
    }

    private void loadDataSementara() {
        getDataSementara((DefaultTableModel) tbl_data_sementara.getModel());
        btn_ubah.setText("TAMBAH");
        btn_hapus.setVisible(false);
        btn_cancel_sementara.setVisible(false);
    }

    // showPanel() - Mengatur tampilan panel utama
    private void showPanel() {
        panelMain.removeAll();// Menghapus semua komponen di panel utama
        panelMain.add(new MenuSewa(userID));// Menambahkan panel MenuKonsol ke panel utama
        panelMain.repaint();// Menggambar ulang panel utama
        panelMain.revalidate();// Memastikan perubahan diterapkan
    }

    // resetForm() - Mengosongkan input form Konsol
    private void resetForm() {
        txt_id.setText("");
        txt_nama_konsol.setText("");
        txt_harga_perhari.setText("");
    }

    private void resetFormKonsol() {
        txt_id_konsol.setText("");
        txt_nama_konsol.setText("");
        txt_harga_perhari.setText("");
        txt_jumlah.setText("");
    }

    private void aktifKonsol() {
        btn_set_konsol.setEnabled(true);
        txt_id_konsol.setEnabled(true);
        txt_nama_konsol.setEnabled(true);
        txt_harga_perhari.setEnabled(true);
    }

    private void nonAktifKonsol() {
        btn_set_konsol.setEnabled(false);
        txt_id_konsol.setEnabled(false);
        txt_nama_konsol.setEnabled(false);
        txt_harga_perhari.setEnabled(false);
    }

    // setTabelModel() - Mengatur model tabel dengan kolom-kolom yang sesuai
    private void setTabelModel() {
        String[] columnNames = {
            "No",
            "ID Sewa",
            "Tanggal Sewa",
            "Tanggal Kembali",
            "Total",
            "Nama Pelanggan",
            "Nama User"
        };
        DefaultTableModel model = new DefaultTableModel(columnNames, 0); // Membuat model tabel dengan kolom yang ditentukan
        tbl_data.setModel(model); // Mengatur model tabel untuk JTable
        loadData(); // Memuat data ke dalam tabel
    }

    // getData() - Mendapatkan data Konsol dari database dengan batasan jumlah data per halaman
    private void getData(int startIndex, int entriesPage, DefaultTableModel model) {
        model.setRowCount(0); // Mengosongkan data yang ada di tabel

        try {
            String sql = "SELECT sw.ID_Sewa, sw.Tanggal_Sewa, sw.Tanggal_Pengembalian, sw.Total, "
                    + "plgn.Nama AS NamaPelanggan, usr.Nama_User AS NamaUser "
                    + "FROM tbl_sewa sw "
                    + "INNER JOIN tbl_pelanggan plgn ON plgn.ID_Pelanggan = sw.ID_Pelanggan "
                    + "INNER JOIN tbl_user usr ON usr.ID_User = sw.ID_User "
                    + "ORDER BY sw.ID_Sewa ASC LIMIT ?, ?";
            // Query dengan limit berdasarkan halaman

            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setInt(1, startIndex); // Indeks awal
                st.setInt(2, entriesPage); // Jumlah data per halaman
                ResultSet rs = st.executeQuery(); // Eksekusi query

                int no = startIndex + 1;

                while (rs.next()) {
                    // Ambil data dari ResultSet
                    String IdSewa = rs.getString("ID_Sewa");
                    String TanggalSewa = rs.getString("Tanggal_Sewa");
                    String TanggalKembali = rs.getString("Tanggal_Pengembalian");
                    String TotalSewa = rs.getString("Total");
                    String NamaPelanggan = rs.getString("NamaPelanggan");
                    String NamaUser = rs.getString("NamaUser");

                    // Tambahkan ke model tabel
                    Object[] rowData = {"   " + no++, IdSewa, TanggalSewa, TanggalKembali, TotalSewa, NamaPelanggan, NamaUser};
                    model.addRow(rowData); // Menambahkan baris data ke dalam tabel
                }
            }
        } catch (Exception e) {
            Logger.getLogger(MenuSewa.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    // setTabelModel() - Mengatur model tabel dengan kolom-kolom yang sesuai
    private void setTabelModelSementara() {
        String[] columnNames = {
            "No",
            "ID",
            "Nama",
            "Jumlah Sewa",
            "Harga Perhari"
        };
        DefaultTableModel model = new DefaultTableModel(columnNames, 0); // Membuat model tabel dengan kolom yang ditentukan
        tbl_data_sementara.setModel(model); // Mengatur model tabel untuk JTable
        loadData(); // Memuat data ke dalam tabel
    }

    // setTabelModel() - Mengatur model tabel dengan kolom-kolom yang sesuai
    private void setTabelModelDetail() {
        String[] columnNames = {
            "No",
            "ID",
            "ID Konsol",
            "Nama Konsol",
            "Jumlah",
            "Status Pinjam"
        };
        DefaultTableModel model = new DefaultTableModel(columnNames, 0); // Membuat model tabel dengan kolom yang ditentukan
        tbl_data_detail.setModel(model); // Mengatur model tabel untuk JTable
        loadData(); // Memuat data ke dalam tabel
    }

    private void getDataDetail(DefaultTableModel model, String id) {
        model.setRowCount(0); // Mengosongkan data yang ada di tabel

        try {
            // Pastikan ada spasi di antara setiap bagian query
            String sql = "SELECT swd.ID_Sewa, knsl.ID_Konsol, knsl.Nama_Konsol, swd.Jumlah_Sewa, swd.Status_Sewa "
                    + "FROM tbl_detail_sewa swd "
                    + "INNER JOIN tbl_konsol knsl ON knsl.ID_Konsol = swd.ID_Konsol "
                    + "WHERE swd.ID_Sewa = ? "
                    + "ORDER BY swd.ID_Sewa ASC";

            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, id); // Menggunakan parameterized query untuk keamanan
                ResultSet rs = st.executeQuery(); // Eksekusi query

                int no = 1;

                while (rs.next()) {
                    // Ambil data dari ResultSet
                    String IdSewa = rs.getString("ID_Sewa");
                    String IdKonsol = rs.getString("ID_Konsol");
                    String NamaKonsol = rs.getString("Nama_Konsol");
                    String JumlahSewa = rs.getString("Jumlah_Sewa");
                    String StatusSewa = rs.getString("Status_Sewa");

                    // Tambahkan ke model tabel
                    Object[] rowData = {"   " + no++, IdSewa, IdKonsol, NamaKonsol, JumlahSewa, StatusSewa};
                    model.addRow(rowData); // Menambahkan baris data ke dalam tabel
                }
            }
        } catch (Exception e) {
            Logger.getLogger(MenuSewa.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void getDataSementara(DefaultTableModel model) {
        model.setRowCount(0); // Mengosongkan data yang ada di tabel

        try {
            String sql = "SELECT * FROM tbl_sementara";
            // Query dengan limit berdasarkan halaman

            try (PreparedStatement st = con.prepareStatement(sql)) {
                ResultSet rs = st.executeQuery(); // Eksekusi query

                int no = 1;

                while (rs.next()) {
                    // Ambil data dari ResultSet
                    String IdKonsol = rs.getString("ID_Konsol");
                    String NamaKonsol = rs.getString("Nama_Konsol");
                    String JumlahSewa = rs.getString("Jumlah_Sewa");
                    String HargaPerhari = rs.getString("Harga_Perhari");

                    // Tambahkan ke model tabel
                    Object[] rowData = {"   " + no++, IdKonsol, NamaKonsol, JumlahSewa, HargaPerhari};
                    model.addRow(rowData); // Menambahkan baris data ke dalam tabel
                }
            }
        } catch (Exception e) {
            Logger.getLogger(MenuSewa.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    // setIDKonsol() - Mengatur ID Konsol secara otomatis
    private String setIDSewa() throws SQLException {
        String urutan = null;
        Date now = new Date();
        SimpleDateFormat noFormat = new SimpleDateFormat("yyMM"); // Format tanggal sebagai bagian dari ID
        String no = noFormat.format(now);

        String sql = "SELECT RIGHT(ID_Sewa, 3) AS Nomor FROM tbl_sewa WHERE ID_Sewa LIKE '" + no + "%' ORDER BY ID_Sewa DESC LIMIT 1";

        try (PreparedStatement st = con.prepareStatement(sql)) {
            ResultSet rs = st.executeQuery(); // Eksekusi query

            if (rs.next()) {
                int nomor = Integer.parseInt(rs.getString("Nomor")) + 1; // Menambah nomor urut
                urutan = no + String.format("%03d", nomor); // Format ID baru (tanpa "KSL")
            } else {
                urutan = no + "001"; // ID awal jika tidak ada data (tanpa "KSL")
            }
        } catch (SQLException e) {
            java.util.logging.Logger.getLogger(MenuSewa.class.getName()).log(Level.SEVERE, null, e);
        }
        return urutan;
    }

    private void setPelanggan() {
        boolean closable = true;
        DataPelanggan pelanggan = new DataPelanggan(null, closable);
        pelanggan.setVisible(true);

        txt_id_pelanggan.setText(pelanggan.getIdPelanggan());
        txt_nama_pelanggan.setText(pelanggan.getNamaPelanggan());
        txt_tlp_pelanggan.setText(pelanggan.getTeleponPelangggan());
        txt_alamat.setText(pelanggan.getAlamatPelanggan());

        txt_id_pelanggan.setEnabled(false);
        txt_nama_pelanggan.setEnabled(false);
        txt_tlp_pelanggan.setEnabled(false);
        txt_alamat.setEnabled(false);
    }

    private void setKonsol() {
        boolean closable = true;
        DataKonsol konsol = new DataKonsol(null, closable);
        konsol.setVisible(true);

        txt_id_konsol.setText(konsol.getIdKonsol());
        txt_nama_konsol.setText(konsol.getNamaKonsol());
        txt_harga_perhari.setText(konsol.getHargaPerhari());

        txt_id_konsol.setEnabled(false);
        txt_nama_konsol.setEnabled(false);
        txt_harga_perhari.setEnabled(false);
    }

    private void insertData() {
        String IdSewa = txt_id.getText();
        String tglSewa = txt_tgl_sewa.getText();
        String tglKembali = txt_tgl_kembali.getText();
        String IdPelanggan = txt_id_pelanggan.getText();

        // Validasi input data
        if (IdSewa.isEmpty() || tglSewa.isEmpty() || tglKembali.isEmpty() || IdPelanggan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validasi format tanggal (contoh menggunakan SimpleDateFormat)
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            sdf.parse(tglSewa);
            sdf.parse(tglKembali);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Format tanggal tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Hitung total sewa sebelum insert
        int totalSewa = getTotalSewa(IdSewa, tglSewa, tglKembali);
        jLabel24.setText(String.valueOf(totalSewa));
        // Insert data ke database
        try {
            String sql = "INSERT INTO tbl_sewa (ID_Sewa, Tanggal_Sewa, Tanggal_Pengembalian, Total, ID_Pelanggan, ID_User) VALUES (?,?,?,?,?,?)";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, IdSewa);
                st.setString(2, tglSewa);
                st.setString(3, tglKembali);
                st.setInt(4, totalSewa);
                st.setString(5, IdPelanggan);
                st.setString(6, userID);

                int rowInserted = st.executeUpdate(); // Menjalankan perintah insert
                if (rowInserted > 0) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
                    insertDataDetail();
                    insertDataSementara();
                    resetForm(); // Kosongkan text field setelah data berhasil ditambahkan
                    loadData();  // Memuat data ke tampilan JTable atau komponen lainnya
                    showPanel();
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(MenuSewa.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    // insertData() - Menambahkan data Konsol ke database
    private void insertDataDetail() {
        String IdSewa = txt_id.getText();

        // Insert data ke database
        try {
            String sql = "INSERT INTO tbl_detail_sewa (ID_Sewa, ID_Konsol, Jumlah_Sewa, Status_Sewa, HargaPerHari) "
                    + "SELECT '" + IdSewa + "', ID_Konsol, Jumlah_Sewa, Status_Sewa, Harga_Perhari FROM tbl_sementara";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.executeUpdate();
            }
        } catch (SQLException e) {
            Logger.getLogger(MenuSewa.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private boolean cekStok(String IdKonsol, int JumlahSewa) {
        try {
            String sql = "SELECT Stock FROM tbl_konsol WHERE ID_Konsol=?";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, IdKonsol);

                ResultSet rs = st.executeQuery();

                if (rs.next()) {
                    int stokTersedia = rs.getInt("Stock");
                    return JumlahSewa <= stokTersedia;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return false;
    }

    // insertData() - Menambahkan data Konsol ke database
    // insertDataSementara() - Menambahkan data Konsol ke database
    private void insertDataSementara() {
        String IdKonsol = txt_id_konsol.getText();
        String NamaKonsol = txt_nama_konsol.getText();
        int JumlahSewa = Integer.parseInt(txt_jumlah.getText());
        String HargaPerhari = txt_harga_perhari.getText();
        String StatusSewa = "Sedang diSewa";

        // Validasi input data
        if (IdKonsol.isEmpty() || NamaKonsol.isEmpty() || HargaPerhari.isEmpty() || StatusSewa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Diisi!", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!cekStok(IdKonsol, JumlahSewa)) {
            JOptionPane.showMessageDialog(this, "Stok Konsol Tidak Tersedia !", "Peringatan", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String sql = "INSERT INTO tbl_sementara (ID_Konsol, Nama_Konsol, Jumlah_Sewa, Harga_Perhari, Status_Sewa) VALUES (?,?,?,?,?)";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, IdKonsol);
                st.setString(2, NamaKonsol);
                st.setInt(3, JumlahSewa); // Menggunakan integer untuk JumlahSewa
                st.setDouble(4, Double.parseDouble(HargaPerhari)); // Menggunakan double untuk HargaPerhari
                st.setString(5, StatusSewa);

                st.executeUpdate(); // Menjalankan perintah insert

                loadDataSementara(); // Memuat data sementara

                // Konfirmasi untuk menambah konsol lagi atau tidak
                if (JOptionPane.showConfirmDialog(this, "Mau Tambah Konsol?", "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    resetFormKonsol(); // Reset form konsol jika ingin menambah konsol lagi
                    btn_set_konsol.requestFocus(); // Fokuskan tombol untuk tambah konsol
                } else {
                    resetFormKonsol(); // Reset form konsol jika tidak menambah konsol lagi
                    btn_simpan.requestFocus(); // Fokuskan tombol simpan
                    btn_simpan.setEnabled(true); // Aktifkan tombol simpan
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(MenuSewa.class.getName()).log(Level.SEVERE, "Error saat insert data", e);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private int getTotalSewa(String idSewa, String tglSewa, String tglKembali) {
        int totalSewa = 0;
        // Query SQL untuk menghitung total sewa
        String sql = "SELECT (DATEDIFF(day, ?, ?) * Harga_PerHari) AS TotalSewa "
                + "FROM tbl_sewa s "
                + "INNER JOIN tbl_konsol k ON s.ID_Konsol = k.ID_Konsol "
                + "WHERE s.ID_Sewa = ?";

        try (PreparedStatement st = con.prepareStatement(sql)) {
            st.setString(1, tglSewa);
            st.setString(2, tglKembali);
            st.setString(3, idSewa);

            ResultSet rs = st.executeQuery();
            if (rs.next()) {
                return rs.getInt("TotalSewa");
            }
        } catch (SQLException e) {
            // Tangani error
        }
        return totalSewa; // Atau nilai default lainnya jika terjadi error
    }

    // dataTabel() - Menampilkan data Konsol dari JTable ke dalam form untuk diperbarui
    private void dataTabel() {
        panelView.setVisible(false); // Menyembunyikan panel view
        panelAdd.setVisible(true); // Menampilkan panel tambah/edit

        int row = tbl_data.getSelectedRow(); // Mendapatkan baris yang dipilih pada tabel
        jLabel7.setText("PERBARUI DATA Konsol"); // Mengubah teks label menjadi "PERBARUI DATA Konsol"
        txt_id.setEnabled(false); // Menonaktifkan field ID Konsol agar tidak bisa diedit
        String id = tbl_data.getModel().getValueAt(row, 0).toString();

        // Mengisi field form dengan data dari baris yang dipilih
        txt_id.setText(tbl_data.getValueAt(row, 0).toString());

    }

    // updateData() - Memperbarui data Konsol di database
    private void updateData() {
        String IdKonsol = txt_id_konsol.getText();
        String JumlahSewa = txt_jumlah.getText();

        // Validasi input data
        if (IdKonsol.isEmpty() || JumlahSewa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Dipilih dan Diisi!", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Update data ke database
        try {
            // Memperbaiki query untuk memasukkan nilai Stock, Status, HargaPerjam, dan HargaPerhari
            String sql = "UPDATE tbl_sementara SET Jumlah_Sewa=? WHERE ID_Konsol=?";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, JumlahSewa); // Set Harga per Hari
                st.setString(2, IdKonsol);

//                int totalSewa = getTotalSewa(IdSewa, tglSewa, tglKembali);
//                jLabel24.setText(String.valueOf(totalSewa));
                int rowUpdated = st.executeUpdate(); // Menjalankan perintah update
                if (rowUpdated > 0) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui");
                    resetFormKonsol(); // Kosongkan form setelah data diperbarui
                    loadDataSementara();  // Refresh data di JTable
                    aktifKonsol();
                    btn_simpan.setEnabled(true);
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(MenuSewa.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void hapusData() {
        int selectedRow = tbl_data_sementara.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; // Keluar dari metode jika tidak ada baris yang dipilih
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah yakin ingin menghapus data ini ?",
                "Konfirmasi Hapus Data",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            String id = tbl_data_sementara.getValueAt(selectedRow, 1).toString();
            try {
                String sql = "DELETE FROM tbl_sementara WHERE ID_Konsol=?";
                try (PreparedStatement st = con.prepareStatement(sql)) {
                    st.setString(1, id);
                    int rowDeleted = st.executeUpdate();

//                    int totalSewa = getTotalSewa(id);
//                    if (totalSewa > 0) {
//                        jLabel24.setText(String.valueOf(totalSewa));
//                    } else {
//                        jLabel24.setText("Total");
//                    }
                    if (rowDeleted > 0) {
                        JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                    } else {
                        JOptionPane.showMessageDialog(this, "Data Gagal Dihapus");
                    }

                    btn_ubah.setText("TAMBAH");
                    aktifKonsol();
                }
            } catch (SQLException e) {
                Logger.getLogger(MenuSewa.class.getName()).log(Level.SEVERE, null, e);
            }
        }
        resetFormKonsol();
        loadDataSementara();
    }

    private void hapusDataSementara() {
        try {
            String sql = "DELETE FROM tbl_sementara";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.executeUpdate();
            }
        } catch (SQLException e) {
            Logger.getLogger(MenuSewa.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void dataTabelSementara() {
        int row = tbl_data_sementara.getSelectedRow();
        if (row != -1) {
            nonAktifKonsol();

            String id = tbl_data_sementara.getValueAt(row, 1).toString();
            txt_id_konsol.setText(tbl_data_sementara.getValueAt(row, 1).toString());
            txt_nama_konsol.setText(tbl_data_sementara.getValueAt(row, 2).toString());
            txt_harga_perhari.setText(tbl_data_sementara.getValueAt(row, 3).toString());

            txt_jumlah.requestFocus();
        }
    }

    // searchData() - Mencari data Konsol berdasarkan nama atau alamat
    private void searchData() {
        String kataKunci = txt_search.getText();

        DefaultTableModel model = (DefaultTableModel) tbl_data.getModel();
        model.setRowCount(0);

        try {
            String sql = "SELECT sw.ID_Sewa, sw.Tanggal_Sewa, sw.Tanggal_Pengembalian, sw.Total, plgn.Nama_Pelanggan, usr.Nama_User"
                    + "FROM tbl_sewa sw"
                    + "INNER JOIN tbl_pelanggan plgn ON plgn.ID_Pelanggan = sw.ID_Pelanggan"
                    + "INNER JOIN tbl_user usr ON usr.ID_User = sw.ID_User"
                    + "WHERE sw.ID_Sewa LIKE ? OR plgn.Nama_Pelanggan LIKE ?";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                st.setString(1, "%" + kataKunci + "%");
                st.setString(2, "%" + kataKunci + "%");
                ResultSet rs = st.executeQuery();

                int no = 1;

                while (rs.next()) {
                    String idSewa = rs.getString("ID_Sewa");
                    String tanggalSewa = rs.getString("Tanggal_Sewa");
                    String tanggalKembali = rs.getString("Tanggal_Pengembalian");
                    String totalSewa = rs.getString("Total");
                    String namaPelanggan = rs.getString("Nama_Pelanggan");
                    String namaUser = rs.getString("Nama_User");

                    Object[] rowData = {"   " + no++, idSewa, tanggalSewa, tanggalKembali, totalSewa, namaPelanggan, namaUser};
                    model.addRow(rowData);
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(MenuSewa.class.getName()).log(Level.SEVERE, null, e);
        }
    }

}
